{% set version = "1.1.3" %}

package:
  name: eagle
  version: {{ version }}

source:
  url: https://github.com/tony-kuo/eagle/releases/tag/v{{ version }}/eagle-{{ version }}.zip
  sha256: e984aaf445c8241263d71485ddc88e43e83e7692

requirements:
  build:
    - make
    - {{ compiler('c') }} 
  host:
    - htslib
    - ncurses
    - zlib

about:
  home: https://github.com/tony-kuo/eagle
  license: GPL-3.0
  license_file: COPYING
  summary: Explicit Alternative Genome Likelihood Evaluator

test:
  commands:
    - eagle --help
    - eagle-rc --help

extra:
  additional-platforms:
    - linux-aarch64
    - osx-arm64
  identifiers:
    - tony-kuo:eagle
